require("options")
require("plugins/catppuccin")
require("plugins/treesitter")
require("plugins/feline")
require("plugins/telescope")
require("plugins/lspconfig")
require("plugins/which-key")
require("plugins/gitsigns")
