---
keys:
  - &dixslyf-pgp 696e2d91121faeef3057400883e06ba3516ce57e
  - &shiba age18qeqs7gvds09hdcf80rrzr74khdk3s9srdp2asv6v4w9vnqr3cssuq9wxe
  - &husky age15mk8nlv652c4lw3yspshsht28ckxxkn3lunyqcmx238enkk3cdpsk4szq4
  - &alpha age1gjuaev2c8dx6r66a975uk8fd59k3e2p3ksyzqxg2asvmcvasde3ss29y3m
  - &bravo age1vsflpyynfjxmy2dgxlku4pdk90yccsxpta0l9fntxusyfhvqegestnhcy3
  - &delta age1g8sxyyhpr79y2l9qql2tqd7q7795s4wcleaqca3wzp2rfs4lge8sv9h6uv
creation_rules:
  - path_regex: home-manager/users/shiba/*
    key_groups:
      - pgp:
          - *dixslyf-pgp
        age:
          - *shiba
  - path_regex: home-manager/users/husky/*
    key_groups:
      - pgp:
          - *dixslyf-pgp
        age:
          - *husky
  - path_regex: nixos/hosts/alpha/sops/secrets.yaml$
    key_groups:
      - pgp:
          - *dixslyf-pgp
        age:
          - *alpha
  - path_regex: nixos/hosts/bravo/sops/secrets.yaml$
    key_groups:
      - pgp:
          - *dixslyf-pgp
        age:
          - *bravo
  - path_regex: nixos/hosts/delta/sops/secrets.yaml$
    key_groups:
      - pgp:
          - *dixslyf-pgp
        age:
          - *delta
