# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "none";
      fsType = "tmpfs";
    };

  fileSystems."/efi" =
    { device = "/dev/disk/by-uuid/A641-BF45";
      fsType = "vfat";
    };

  boot.initrd.luks.devices."boot".device = "/dev/disk/by-uuid/a7c56f24-d4ea-424b-9398-e3ee6a882d40";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/971d06b6-fc2c-483a-b20f-0d4240ffbbe7";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/854bb237-57b8-4d7a-b622-f3f282fbc7d5";

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/2f8242e4-6b35-42bf-a68d-63bd87faf388";
      fsType = "btrfs";
      options = [ "subvol=@persist" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/2f8242e4-6b35-42bf-a68d-63bd87faf388";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  boot.initrd.luks.devices."home".device = "/dev/disk/by-uuid/06d59406-97c7-4bb8-a620-152169bcd00d";

  fileSystems."/persist/home" =
    { device = "/dev/disk/by-uuid/e506b57c-6940-40a3-9ace-79d0211752ac";
      fsType = "btrfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/5f5a0bd0-5fd6-4773-b3f5-8d2e607d1213"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s20f0u2u4.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
