# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "uas" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
  };

  fileSystems."/efi" = {
    device = "/dev/disk/by-uuid/CDE8-57B1";
    fsType = "vfat";
  };

  boot.initrd.luks.devices."boot".device = "/dev/disk/by-uuid/cbc19986-1e63-4af0-9730-bbbe2f3b28f7";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/40fcf0a0-13cc-47c4-83bb-f83df975df8e";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/b9004b54-8415-4754-81c4-61ae7c8580bd";

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/5315a5dd-a383-409a-b8b0-33bbc9d57a17";
    fsType = "btrfs";
    options = ["subvol=@persist"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/5315a5dd-a383-409a-b8b0-33bbc9d57a17";
    fsType = "btrfs";
    options = ["subvol=@nix"];
  };

  boot.initrd.luks.devices."home".device = "/dev/disk/by-uuid/06d59406-97c7-4bb8-a620-152169bcd00d";

  fileSystems."/persist/home" = {
    device = "/dev/disk/by-uuid/e506b57c-6940-40a3-9ace-79d0211752ac";
    fsType = "btrfs";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/24ea210c-9f50-4de4-8900-49a851dbe94e";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s20f0u2u4.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
