---
name: Build and cache package from flake's Nixpkgs

on:
  workflow_dispatch:
    inputs:
      system:
        description: "The system to build the package for."
        type: string
        default: "x86_64-linux"
        required: true
      package:
        description: "The name of the package to build."
        type: string
        required: true

run-name: "Build and cache ${{ inputs.package }} (${{ inputs.system }}) from flake's Nixpkgs"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Build and cache
        uses: ./.github/actions/build
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          derivation: ".#inputs.nixpkgs.legacyPackages.${{ inputs.system }}.${{ inputs.package }}"
